import {$,$$,state,loadPrefs,loadSavedData,clearSavedData,icon,text} from './core.js';
import {settingsMarkup,initThemeUI,applyTheme} from './theme.js';
import {searchMarkup,initSearch,terms,resetSearch} from './search.js';
import {L,home,collection,recipeDetail,ingredientDetail,genericDetail,helpMarkup,toolbarMarkup,dataControlsMarkup,bindCommon,initHelpAndToolbar,initDataIO} from './ui.js';

async function loadDefault(force=false){if(!force){const saved=loadSavedData();if(saved)return saved}const r=await fetch('./data/demo.json',{cache:'no-store'});if(!r.ok)throw new Error(`data ${r.status}`);const d=await r.json();if(force)clearSavedData();return d}
function navMarkup(){return `<nav class="nav" aria-label="Navigation"><button class="btn" data-section="home">Accueil</button><button class="btn" data-section="recipes">Recettes</button><button class="btn" data-section="ingredients">Ingrédients</button><button class="btn" data-section="techniques">Techniques & astuces</button><button class="btn" data-section="equipment">Matériel</button><button class="btn" data-section="library">Bibliothèque</button></nav>`}
function shell(){document.body.innerHTML=`<header id="siteHeader" class="site-header"><div class="wrap"><div class="topbar"><div class="brand" id="brandHome"><span class="brand-dot"></span>🍽️ CuisineX</div>${searchMarkup()}<span class="grow"></span><div id="langSwitch" class="lang-switch"><button class="btn lang-btn" data-lang="fr">🇫🇷 <span>FR</span></button><button class="btn lang-btn" data-lang="en">🇬🇧 <span>EN</span></button></div><button class="icon-btn" id="openHelpHeader" title="Aide contextuelle">${icon('help')}</button><button class="icon-btn" id="openSettings" title="Paramètres">${icon('gear')}</button></div>${navMarkup()}</div></header><main id="app" class="wrap"></main>${settingsMarkup()}${helpMarkup()}${toolbarMarkup()}<footer id="siteFooter"></footer>`}
function localizedNav(){const map={home:'Accueil',recipes:L('recipes'),ingredients:L('ingredients'),techniques:L('techniques'),equipment:L('equipment'),library:L('library')};$$('[data-section]').forEach(b=>{b.textContent=map[b.dataset.section]||b.dataset.section;b.classList.toggle('active',b.dataset.section===state.section)});$$('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang));document.documentElement.lang=state.lang}
function globalSearchView(){const ts=terms();if(!ts.length)return null;const groups=['recipes','ingredients','techniques','equipment','library'].filter(t=>state.prefs.searchScopes.includes(t));return `<div class="panel"><h1>${L('search')}</h1><p class="muted">${ts.map(t=>`#${t}`).join(' · ')}</p></div>${groups.map(t=>`<section class="section"><div class="section-head"><h2>${({recipes:L('recipes'),ingredients:L('ingredients'),techniques:L('techniques'),equipment:L('equipment'),library:L('library')})[t]}</h2></div><div class="section-body">${collection(t)}</div></section>`).join('')}`}
export function render(){localizedNav();applyTheme();const app=$('#app');const global=globalSearchView();if(global&&!state.detail){app.innerHTML=global}else if(state.detail){const {type,id}=state.detail;const x=(state.data?.[type]||[]).find(o=>o.id===id);if(!x){app.innerHTML='<div class="panel">Objet introuvable.</div>'}else if(type==='recipes')app.innerHTML=recipeDetail(x);else if(type==='ingredients')app.innerHTML=ingredientDetail(x);else app.innerHTML=genericDetail(x,type)}else if(state.section==='home'){app.innerHTML=home()+`<section class="section"><div class="section-head"><h2>Données du prototype</h2></div><div class="section-body">${dataControlsMarkup()}</div></section>`}else{app.innerHTML=`<div class="panel"><h1>${({recipes:L('recipes'),ingredients:L('ingredients'),techniques:L('techniques'),equipment:L('equipment'),library:L('library')})[state.section]}</h1></div>${collection(state.section)}`}
  bindCommon(render);initDataIO(loadDefault,render);bindShellEvents();
}
function bindShellEvents(){$$('[data-section]').forEach(b=>b.onclick=()=>{state.section=b.dataset.section;state.detail=null;state.page=1;resetSearch();render()});$$('.lang-btn').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;state.prefs.defaultLanguage=state.lang;localStorage.setItem('cuisinex.preview.prefs.v3',JSON.stringify(state.prefs));render()});$('#brandHome').onclick=()=>{state.section='home';state.detail=null;resetSearch();render()};$('#openHelpHeader').onclick=()=>$('#helpDrawer').classList.toggle('open')}
async function init(){loadPrefs();state.data=await loadDefault();shell();initSearch();initThemeUI();initHelpAndToolbar(render);document.addEventListener('cuisinex:search-change',()=>{state.page=1;render()});document.addEventListener('cuisinex:open',e=>{state.detail=e.detail;state.section=e.detail.type;state.page=1;render();scrollTo({top:0,behavior:'smooth'})});render()}
init().catch(err=>{document.body.innerHTML=`<pre style="padding:20px">CuisineX preview error: ${String(err)}</pre>`});
