import {$,$$,state,savePrefs,icon,toast} from './core.js';
import {openFloating} from './floating.js';

const suffixes=['ingredients','timeline','process','nutrition','technical','tips','trials','media','identity','culinary','gallery','notes','tags','hero','search','sections','data','intro','architecture','main'];
function config(){state.prefs.contextTheme=state.prefs.contextTheme||{enabled:false,scope:'item',global:{},types:{},items:{}};return state.prefs.contextTheme}
function sectionType(section){const id=section.id||'section';const suffix=suffixes.find(s=>id.endsWith(`-${s}`))||'section';return `${state.section}:${suffix}`}
function styleFor(scope,target){const c=config();if(scope==='all')return c.global||{};if(scope==='type')return c.types?.[target.type]||{};return c.items?.[target.id]||{}}
function setStyle(scope,target,style){const c=config();if(scope==='all')c.global=style;else if(scope==='type'){c.types=c.types||{};c.types[target.type]=style}else{c.items=c.items||{};c.items[target.id]=style}savePrefs();applyContextTheme()}
function targetFromSection(section){return {kind:'section',id:section.id||'',type:section.dataset.themeType||sectionType(section),title:section.querySelector('.section-head h2,.section-head h3')?.textContent?.trim()||section.id||'Section'}}
function targetFromWindow(panel){const key=panel.dataset.floatingKey||panel.id||'window';return {kind:'window',id:`window:${key}`,type:'window:floating',title:panel.querySelector('.floating-head strong')?.textContent?.trim()||key}}
function setVars(el,s={},kind='section'){const m=kind==='window'?{background:'--cx-window-bg',border:'--cx-window-border',text:'--cx-window-text',accent:'--cx-window-accent'}:{background:'--cx-section-bg',border:'--cx-section-border',text:'--cx-section-text',accent:'--cx-section-accent'};for(const [k,v] of Object.entries(m)){if(s[k])el.style.setProperty(v,s[k]);else el.style.removeProperty(v)}}
function mergedStyle(target){const c=config();return {...(c.global||{}),...(c.types?.[target.type]||{}),...(c.items?.[target.id]||{})}}
export function applyContextTheme(){const c=config();$$('.section').forEach(section=>{section.dataset.themeType=sectionType(section);const target=targetFromSection(section);setVars(section,mergedStyle(target),'section')});$$('[data-floating-key]').filter(p=>p.id!=='quickTools').forEach(panel=>{const target=targetFromWindow(panel);panel.dataset.themeType=target.type;setVars(panel,mergedStyle(target),'window')});document.body.classList.toggle('context-theme-mode',!!c.enabled)}
function currentTarget(){if(state.themeTarget)return state.themeTarget;const first=$('.section');return first?targetFromSection(first):{kind:'section',id:'',type:`${state.section}:section`,title:'Aucun élément'}}
function syncEditor(){const box=$('#contextThemeBox');if(!box)return;const c=config(),target=currentTarget();$('#contextThemeEnabled').checked=!!c.enabled;$('#contextThemeScope').value=c.scope||'item';$('#contextThemeTarget').textContent=`${target.kind==='window'?'Fenêtre':'Section'} · ${target.title}`;const s=styleFor(c.scope||'item',target),fallback={background:'#ffffff',border:'#c9d8ee',text:'#142033',accent:state.prefs.primary||'#2563eb'};for(const k of ['background','border','text','accent']){const e=$(`#ctx-${k}`);if(e)e.value=s[k]||fallback[k]}}
function editorMarkup(){return `<div id="contextThemeBox" class="context-theme-box"><strong>Thème contextuel</strong><label class="context-enable"><input id="contextThemeEnabled" type="checkbox"> Afficher le bouton thème sur les sections et fenêtres</label><div class="field"><label>Cible sélectionnée</label><div id="contextThemeTarget" class="context-target">Aucun élément</div></div><div class="field"><label>Portée</label><select id="contextThemeScope"><option value="all">Tous les éléments contextuels</option><option value="type">Éléments équivalents</option><option value="item">Cet élément seulement</option></select></div><div class="two-col context-colors"><label class="field">Fond<input id="ctx-background" type="color"></label><label class="field">Bordure<input id="ctx-border" type="color"></label><label class="field">Texte<input id="ctx-text" type="color"></label><label class="field">Accent<input id="ctx-accent" type="color"></label></div><button class="btn" id="contextThemeReset">Réinitialiser cette portée</button></div>`}
function bindEditor(){const panel=$('#settingsPanel .floating-body');if(!panel||$('#contextThemeBox'))return;const headerBlock=[...panel.querySelectorAll('strong')].find(x=>x.textContent.trim()==='Header');if(headerBlock)headerBlock.insertAdjacentHTML('beforebegin',`<hr>${editorMarkup()}<hr>`);else panel.insertAdjacentHTML('afterbegin',editorMarkup());syncEditor();$('#contextThemeEnabled').onchange=e=>{config().enabled=e.target.checked;savePrefs();refreshContextTheme();toast(e.target.checked?'Édition contextuelle activée':'Édition contextuelle masquée')};$('#contextThemeScope').onchange=e=>{config().scope=e.target.value;savePrefs();syncEditor()};['background','border','text','accent'].forEach(k=>{$(`#ctx-${k}`).oninput=()=>{const target=currentTarget(),scope=config().scope||'item',current={...styleFor(scope,target),[k]:$(`#ctx-${k}`).value};setStyle(scope,target,current)}});$('#contextThemeReset').onclick=()=>{const c=config(),target=currentTarget();if(c.scope==='all')c.global={};else if(c.scope==='type')delete c.types?.[target.type];else delete c.items?.[target.id];savePrefs();applyContextTheme();syncEditor();toast('Surcharge de thème supprimée')}}
function addSectionButtons(){const enabled=!!config().enabled;$$('.section').forEach(section=>{section.dataset.themeType=sectionType(section);let b=section.querySelector(':scope > .section-head .context-theme-btn');if(!enabled){b?.remove();return}if(!b){b=document.createElement('button');b.type='button';b.className='mini-btn context-theme-btn';b.innerHTML=icon('palette');b.title='Thème de cette section';const actions=section.querySelector(':scope > .section-head .section-actions')||section.querySelector(':scope > .section-head');actions?.prepend(b);b.onclick=e=>{e.stopPropagation();state.themeTarget=targetFromSection(section);syncEditor();openFloating('settings')}}})}
function selectWindowTarget(e){const {key,title}=e.detail||{};if(!key)return;state.themeTarget={kind:'window',id:`window:${key}`,type:'window:floating',title:title||key};syncEditor();openFloating('settings')}
export function refreshContextTheme(){bindEditor();addSectionButtons();applyContextTheme();syncEditor()}
export function initContextTheme(){bindEditor();refreshContextTheme();document.addEventListener('cuisinex:floating-refresh',()=>{applyContextTheme();syncEditor()});document.addEventListener('cuisinex:theme-target',selectWindowTarget)}
