import {$,$$,state,savePrefs,icon} from './core.js';

function cfg(key){state.prefs.windows=state.prefs.windows||{};state.prefs.windows[key]=state.prefs.windows[key]||{locked:false,docked:false,collapsed:false,position:null};return state.prefs.windows[key]}
function headerOffset(){const h=$('#siteHeader');return h?Math.ceil(h.getBoundingClientRect().height)+8:8}
function syncHeaderOffset(){document.documentElement.style.setProperty('--cx-header-offset',`${headerOffset()}px`)}
function persist(key){savePrefs();document.dispatchEvent(new CustomEvent('cuisinex:floating-change',{detail:{key,state:cfg(key)}}))}
function actionsMarkup(key){return `<div class="floating-actions"><button class="mini-btn" data-float-collapse title="Replier / déplier la fenêtre">${icon('minimize')}</button><button class="mini-btn" data-float-lock title="Verrouiller / libérer le déplacement">${icon('unlock')}</button><button class="mini-btn" data-float-dock title="Ancrer / libérer la fenêtre">${icon('anchor')}</button><button class="mini-btn" data-float-close title="Fermer">${icon('close')}</button></div>`}
function ensureActions(panel,key){const head=panel.querySelector('.floating-head');if(!head)return null;let box=head.querySelector('.floating-actions');if(!box){head.insertAdjacentHTML('beforeend',actionsMarkup(key));box=head.querySelector('.floating-actions')}return box}
function syncPanel(panel,key){const c=cfg(key),box=ensureActions(panel,key);panel.classList.toggle('locked',!!c.locked);panel.classList.toggle('docked',!!c.docked);panel.classList.toggle('collapsed-window',!!c.collapsed);if(c.docked){panel.style.left='';panel.style.right='';panel.style.top=''}else if(c.position){panel.style.left=c.position.left||'';panel.style.top=c.position.top||'';panel.style.right='auto'}
  const lock=box?.querySelector('[data-float-lock]'),dock=box?.querySelector('[data-float-dock]'),collapse=box?.querySelector('[data-float-collapse]');if(lock){lock.innerHTML=icon(c.locked?'lock':'unlock');lock.classList.toggle('active',!!c.locked);lock.title=c.locked?'Déverrouiller pour déplacer':'Verrouiller la position'}if(dock)dock.classList.toggle('active',!!c.docked);if(collapse){collapse.innerHTML=icon(c.collapsed?'maximize':'minimize');collapse.title=c.collapsed?'Déplier la fenêtre':'Replier la fenêtre'}}
function makeDraggable(panel,key){const head=panel.querySelector('.floating-head');if(!head||head.dataset.dragBound)return;head.dataset.dragBound='1';let drag=null;head.addEventListener('pointerdown',e=>{const c=cfg(key);if(c.locked||c.docked||e.target.closest('button,input,select,a'))return;const r=panel.getBoundingClientRect();drag={dx:e.clientX-r.left,dy:e.clientY-r.top};head.setPointerCapture?.(e.pointerId)});head.addEventListener('pointermove',e=>{if(!drag)return;const left=Math.max(4,Math.min(innerWidth-panel.offsetWidth-4,e.clientX-drag.dx)),top=Math.max(headerOffset(),Math.min(innerHeight-42,e.clientY-drag.dy));panel.style.left=`${left}px`;panel.style.top=`${top}px`;panel.style.right='auto'});head.addEventListener('pointerup',()=>{if(!drag)return;drag=null;cfg(key).position={left:panel.style.left,top:panel.style.top};persist(key)})}
function bindPanel(panel,key){if(!panel||panel.dataset.floatBound)return;panel.dataset.floatBound='1';panel.dataset.floatingKey=key;ensureActions(panel,key);makeDraggable(panel,key);const head=panel.querySelector('.floating-head');head?.querySelector('[data-float-collapse]')?.addEventListener('click',()=>{cfg(key).collapsed=!cfg(key).collapsed;persist(key);syncPanel(panel,key)});head?.querySelector('[data-float-lock]')?.addEventListener('click',()=>{cfg(key).locked=!cfg(key).locked;persist(key);syncPanel(panel,key)});head?.querySelector('[data-float-dock]')?.addEventListener('click',()=>{const c=cfg(key);c.docked=!c.docked;if(!c.docked&&!c.position)c.position={left:'24px',top:`${headerOffset()+12}px`};persist(key);syncPanel(panel,key)});head?.querySelector('[data-float-close]')?.addEventListener('click',()=>{panel.classList.remove('open');panel.setAttribute('aria-hidden','true')});syncPanel(panel,key)}
export function openFloating(key){const panel=document.querySelector(`[data-floating-key="${key}"]`);if(!panel)return;syncHeaderOffset();syncPanel(panel,key);panel.classList.add('open');panel.setAttribute('aria-hidden','false')}
export function closeFloating(key){const panel=document.querySelector(`[data-floating-key="${key}"]`);if(panel){panel.classList.remove('open');panel.setAttribute('aria-hidden','true')}}
export function initFloatingSystem(){syncHeaderOffset();const map={settings:'#settingsPanel',help:'#helpDrawer',search:'#searchConfigPanel',qr:'#qrPanel'};for(const [key,sel] of Object.entries(map)){const p=$(sel);if(p){p.dataset.floatingKey=key;bindPanel(p,key)}};addEventListener('resize',syncHeaderOffset);if('ResizeObserver' in window&&$('#siteHeader'))new ResizeObserver(syncHeaderOffset).observe($('#siteHeader'))}

export function initMovableToolbar(){const bar=$('#quickTools');if(!bar)return;const key='toolbar',c=cfg(key);bar.classList.toggle('toolbar-locked',!!c.locked);bar.classList.toggle('toolbar-free',!c.docked);if(!c.docked&&c.position){bar.style.left=c.position.left;bar.style.top=c.position.top;bar.style.bottom='auto';bar.style.transform='none'}
  const sync=()=>{const s=cfg(key);bar.classList.toggle('toolbar-locked',!!s.locked);bar.classList.toggle('toolbar-free',!s.docked);$('#toolbarLock')?.classList.toggle('active',!!s.locked);if($('#toolbarLock'))$('#toolbarLock').innerHTML=icon(s.locked?'lock':'unlock');$('#toolbarDock')?.classList.toggle('active',!!s.docked);if(s.docked){bar.style.left='50%';bar.style.bottom='13px';bar.style.top='';bar.style.transform='translateX(-50%)'}else if(s.position){bar.style.left=s.position.left;bar.style.top=s.position.top;bar.style.bottom='auto';bar.style.transform='none'}};
  $('#toolbarLock')?.addEventListener('click',()=>{cfg(key).locked=!cfg(key).locked;persist(key);sync()});$('#toolbarDock')?.addEventListener('click',()=>{const s=cfg(key);s.docked=!s.docked;if(!s.docked&&!s.position){const r=bar.getBoundingClientRect();s.position={left:`${Math.max(6,r.left)}px`,top:`${Math.max(headerOffset(),r.top)}px`}}persist(key);sync()});
  let drag=null;bar.addEventListener('pointerdown',e=>{const s=cfg(key);if(s.locked||s.docked||e.target.closest('button,a,input,select'))return;const r=bar.getBoundingClientRect();drag={dx:e.clientX-r.left,dy:e.clientY-r.top};bar.setPointerCapture?.(e.pointerId)});bar.addEventListener('pointermove',e=>{if(!drag)return;bar.style.left=`${Math.max(4,Math.min(innerWidth-bar.offsetWidth-4,e.clientX-drag.dx))}px`;bar.style.top=`${Math.max(headerOffset(),Math.min(innerHeight-bar.offsetHeight-4,e.clientY-drag.dy))}px`;bar.style.bottom='auto';bar.style.transform='none'});bar.addEventListener('pointerup',()=>{if(!drag)return;drag=null;cfg(key).position={left:bar.style.left,top:bar.style.top};persist(key)});sync()}
