export const LANGUAGES={
  fr:{code:'fr',label:'Français',short:'FR',flag:'🇫🇷',dir:'ltr',source:true},
  en:{code:'en',label:'English',short:'EN',flag:'🇬🇧',dir:'ltr'},
  es:{code:'es',label:'Español',short:'ES',flag:'🇪🇸',dir:'ltr'},
  ru:{code:'ru',label:'Русский',short:'RU',flag:'🇷🇺',dir:'ltr'},
  ar:{code:'ar',label:'العربية',short:'AR',flag:'🌐',dir:'rtl'},
  ps:{code:'ps',label:'پښتو',short:'PS',flag:'🇦🇫',dir:'rtl'}
};
export const ALTERNATE_LANGUAGES=['en','es','ru','ar','ps'];

const UI={
  fr:{home:'Accueil',recipes:'Recettes',ingredients:'Ingrédients',techniques:'Techniques & astuces',equipment:'Matériel',library:'Bibliothèque',search:'Recherche',ingredientsTitle:'Ingrédients',primaryIngredients:'Ingrédients principaux',allIngredients:'Liste des ingrédients',process:'Procédé',nutrition:'Valeurs nutritionnelles',technical:'Données techniques',tips:'Tours de main & liens',trials:'Galerie des essais',timeline:'Chronologie',sources:'Sources',back:'Retour',total:'Durée totale',active:'Temps actif',status:'Statut',allergens:'Allergènes',alcohol:'Alcool',pork:'Porc',concept:'Concept',servings:'Parts',per100g:'Pour 100 g',perServing:'Par portion',nutriscore:'Nutri-Score estimatif'},
  en:{home:'Home',recipes:'Recipes',ingredients:'Ingredients',techniques:'Techniques & tips',equipment:'Equipment',library:'Library',search:'Search',ingredientsTitle:'Ingredients',primaryIngredients:'Main ingredients',allIngredients:'Ingredient list',process:'Method',nutrition:'Nutrition',technical:'Technical data',tips:'Tips & links',trials:'Trial gallery',timeline:'Timeline',sources:'Sources',back:'Back',total:'Total duration',active:'Active time',status:'Status',allergens:'Allergens',alcohol:'Alcohol',pork:'Pork',concept:'Concept',servings:'Servings',per100g:'Per 100 g',perServing:'Per serving',nutriscore:'Estimated Nutri-Score'},
  es:{home:'Inicio',recipes:'Recetas',ingredients:'Ingredientes',techniques:'Técnicas y trucos',equipment:'Material',library:'Biblioteca',search:'Buscar',ingredientsTitle:'Ingredientes',primaryIngredients:'Ingredientes principales',allIngredients:'Lista de ingredientes',process:'Preparación',nutrition:'Valores nutricionales',technical:'Datos técnicos',tips:'Consejos y enlaces',trials:'Galería de pruebas',timeline:'Cronología',sources:'Fuentes',back:'Volver',total:'Duración total',active:'Tiempo activo',status:'Estado',allergens:'Alérgenos',alcohol:'Alcohol',pork:'Cerdo',concept:'Concepto',servings:'Porciones',per100g:'Por 100 g',perServing:'Por porción',nutriscore:'Nutri-Score estimado'},
  ru:{home:'Главная',recipes:'Рецепты',ingredients:'Ингредиенты',techniques:'Техники и советы',equipment:'Инвентарь',library:'Библиотека',search:'Поиск',ingredientsTitle:'Ингредиенты',primaryIngredients:'Основные ингредиенты',allIngredients:'Список ингредиентов',process:'Способ приготовления',nutrition:'Пищевая ценность',technical:'Технические данные',tips:'Приёмы и ссылки',trials:'Галерея тестов',timeline:'Хронология',sources:'Источники',back:'Назад',total:'Общее время',active:'Активное время',status:'Статус',allergens:'Аллергены',alcohol:'Алкоголь',pork:'Свинина',concept:'Концепция',servings:'Порции',per100g:'На 100 г',perServing:'На порцию',nutriscore:'Оценочный Nutri-Score'},
  ar:{home:'الرئيسية',recipes:'الوصفات',ingredients:'المكونات',techniques:'التقنيات والنصائح',equipment:'المعدات',library:'المكتبة',search:'البحث',ingredientsTitle:'المكونات',primaryIngredients:'المكونات الرئيسية',allIngredients:'قائمة المكونات',process:'طريقة التحضير',nutrition:'القيم الغذائية',technical:'البيانات التقنية',tips:'نصائح وروابط',trials:'معرض التجارب',timeline:'التسلسل الزمني',sources:'المصادر',back:'رجوع',total:'المدة الإجمالية',active:'الوقت النشط',status:'الحالة',allergens:'مسببات الحساسية',alcohol:'الكحول',pork:'لحم الخنزير',concept:'المفهوم',servings:'الحصص',per100g:'لكل 100 غ',perServing:'لكل حصة',nutriscore:'Nutri-Score تقديري'},
  ps:{home:'کور',recipes:'ترکیبونه',ingredients:'اجزا',techniques:'تخنیکونه او لارښوونې',equipment:'وسایل',library:'کتابتون',search:'لټون',ingredientsTitle:'اجزا',primaryIngredients:'اصلي اجزا',allIngredients:'د اجزاوو لېست',process:'د چمتو کولو طریقه',nutrition:'غذایي ارزښتونه',technical:'تخنیکي معلومات',tips:'لارښوونې او اړیکې',trials:'د ازموینو ګالري',timeline:'مهالویش',sources:'سرچینې',back:'شاته',total:'ټول وخت',active:'فعال وخت',status:'حالت',allergens:'حساسیتونه',alcohol:'الکول',pork:'د خوګ غوښه',concept:'مفهوم',servings:'برخې',per100g:'په 100 ګرامه کې',perServing:'په هره برخه کې',nutriscore:'اټکلي Nutri-Score'}
};

export function uiLabel(lang,key){return UI[lang]?.[key]??UI.fr[key]??key}
export function languageDirection(lang){return LANGUAGES[lang]?.dir||'ltr'}
export function alternateLanguageOptions(){return ALTERNATE_LANGUAGES.map(code=>{const l=LANGUAGES[code];return `<option value="${code}">${l.flag} ${l.short} · ${l.label}</option>`}).join('')}
