import {$,$$,state,icon} from './core.js';
import {uiLabel} from './i18n.js';

function L(section){return uiLabel(state.lang,section)}
function S(section){const full=L(section);if(section==='home'||section==='concept')return full;return `${[...full].slice(0,3).join('')}…`}
function ensureControls(){const nav=$('#mainNav')||$('.nav');if(!nav)return null;nav.id='mainNav';if(!$('#navMore')){const more=document.createElement('button');more.type='button';more.id='navMore';more.className='btn nav-overflow-trigger';more.innerHTML=icon('more');more.title='Plus de rubriques';nav.append(more);const burger=document.createElement('button');burger.type='button';burger.id='navBurger';burger.className='btn nav-burger-trigger';burger.innerHTML=icon('burger');burger.title='Menu';nav.append(burger);const pop=document.createElement('div');pop.id='navOverflow';pop.className='nav-overflow-panel';nav.insertAdjacentElement('afterend',pop);more.onclick=e=>{e.stopPropagation();pop.classList.toggle('open');renderOverflow('middle')};burger.onclick=e=>{e.stopPropagation();pop.classList.toggle('open');renderOverflow('all')}}return nav}
function originals(){return $$('#mainNav [data-section]')}
function renderOverflow(mode){const pop=$('#navOverflow');if(!pop)return;const items=originals(),selected=mode==='all'?items:items.slice(1,-1);pop.innerHTML=selected.map(b=>`<button class="btn ${b.classList.contains('active')?'active':''}" data-nav-proxy="${b.dataset.section}">${L(b.dataset.section)}</button>`).join('');$$('[data-nav-proxy]',pop).forEach(b=>b.onclick=()=>{const original=originals().find(x=>x.dataset.section===b.dataset.navProxy);pop.classList.remove('open');original?.click()})}
function applyLabels(mode){originals().forEach(b=>{const full=L(b.dataset.section);b.dataset.fullLabel=full;b.title=full;b.textContent=mode==='compact'?S(b.dataset.section):full})}
function setMode(mode){document.body.classList.remove('nav-full','nav-compact','nav-overflow','nav-burger');document.body.classList.add(`nav-${mode}`);applyLabels(mode==='compact'?'compact':'full');const pop=$('#navOverflow');if(pop&&!['overflow','burger'].includes(mode))pop.classList.remove('open')}
function navFits(nav){return nav.scrollWidth<=nav.clientWidth+2}
export function refreshResponsiveNav(){const nav=ensureControls();if(!nav)return;setMode('full');if(navFits(nav)&&innerWidth>=720)return;setMode('compact');if(navFits(nav)&&innerWidth>=640)return;if(innerWidth>=560){setMode('overflow');if($('#navOverflow')?.classList.contains('open'))renderOverflow('middle');return}setMode('burger');if($('#navOverflow')?.classList.contains('open'))renderOverflow('all')}
export function initResponsiveNav(){ensureControls();refreshResponsiveNav();addEventListener('resize',refreshResponsiveNav,{passive:true});if('ResizeObserver' in window&&$('#mainNav'))new ResizeObserver(refreshResponsiveNav).observe($('#mainNav'));document.addEventListener('click',e=>{if(!e.target.closest('#mainNav,#navOverflow'))$('#navOverflow')?.classList.remove('open')});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#navOverflow')?.classList.remove('open')})}
