import {$,$$,state,icon} from './core.js';

const labels={
  fr:{home:'Accueil',recipes:'Recettes',ingredients:'Ingrédients',techniques:'Techniques & astuces',equipment:'Matériel',library:'Bibliothèque',concept:'Concept'},
  en:{home:'Home',recipes:'Recipes',ingredients:'Ingredients',techniques:'Techniques & tips',equipment:'Equipment',library:'Library',concept:'Concept'},
  es:{home:'Inicio',recipes:'Recetas',ingredients:'Ingredientes',techniques:'Técnicas y trucos',equipment:'Material',library:'Biblioteca',concept:'Concepto'}
};
function L(section){return labels[state.lang]?.[section]||labels.fr[section]||section}
function ensureControls(){const nav=$('#mainNav')||$('.nav');if(!nav)return null;nav.id='mainNav';if(!$('#navMore')){const more=document.createElement('button');more.type='button';more.id='navMore';more.className='btn nav-overflow-trigger';more.innerHTML=icon('more');more.title='Plus de rubriques';nav.append(more);const burger=document.createElement('button');burger.type='button';burger.id='navBurger';burger.className='btn nav-burger-trigger';burger.innerHTML=icon('burger');burger.title='Menu';nav.append(burger);const pop=document.createElement('div');pop.id='navOverflow';pop.className='nav-overflow-panel';nav.insertAdjacentElement('afterend',pop);more.onclick=e=>{e.stopPropagation();pop.classList.toggle('open');renderOverflow('middle')};burger.onclick=e=>{e.stopPropagation();pop.classList.toggle('open');renderOverflow('all')}}return nav}
function originals(){return $$('#mainNav [data-section]')}
function renderOverflow(mode){const pop=$('#navOverflow');if(!pop)return;const items=originals();const selected=mode==='all'?items:items.slice(1,-1);pop.innerHTML=selected.map(b=>`<button class="btn ${b.classList.contains('active')?'active':''}" data-nav-proxy="${b.dataset.section}">${L(b.dataset.section)}</button>`).join('');$$('[data-nav-proxy]',pop).forEach(b=>b.onclick=()=>{const original=originals().find(x=>x.dataset.section===b.dataset.navProxy);pop.classList.remove('open');original?.click()})}
export function refreshResponsiveNav(){const nav=ensureControls();if(!nav)return;const w=innerWidth,items=originals();document.body.classList.remove('nav-full','nav-compact','nav-overflow','nav-burger');const mode=w>=1040?'full':w>=780?'compact':w>=560?'overflow':'burger';document.body.classList.add(`nav-${mode}`);items.forEach((b,i)=>{const full=L(b.dataset.section);b.dataset.fullLabel=full;b.title=full;if(mode==='compact'&&i>0&&i<items.length-1)b.textContent=`${full.slice(0,3)}…`;else b.textContent=full});if(mode==='overflow'&&$('#navOverflow')?.classList.contains('open'))renderOverflow('middle');if(mode==='burger'&&$('#navOverflow')?.classList.contains('open'))renderOverflow('all')}
export function initResponsiveNav(){ensureControls();refreshResponsiveNav();addEventListener('resize',refreshResponsiveNav,{passive:true});document.addEventListener('click',e=>{if(!e.target.closest('#mainNav,#navOverflow'))$('#navOverflow')?.classList.remove('open')});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#navOverflow')?.classList.remove('open')})}
