import {$,$$,state,normalize,text,savePrefs,allObjects,toast,icon} from './core.js';
export function searchMarkup(){return `<div class="global-search"><input id="globalSearch" type="search" placeholder="Rechercher dans CuisineX…" autocomplete="off"><button class="icon-btn" id="searchConfigBtn" title="Configurer la recherche">${icon('sliders')}</button><button class="icon-btn" id="searchResetBtn" title="Réinitialiser">${icon('reset')}</button></div><div id="tokenRow" class="token-row hidden"></div><div id="searchConfigPanel" class="search-panel search-config hidden"><div class="field"><strong>Mode de saisie</strong><div class="filter-row"><button class="btn" data-search-mode="free">Libre</button><button class="btn" data-search-mode="suggest">Suggestions</button><button class="btn" data-search-mode="tokens">Jetons</button></div></div><div class="field"><strong>Opérateur</strong><div class="filter-row"><button class="btn" data-search-op="and">ET</button><button class="btn" data-search-op="or">OU</button></div></div><div class="field"><strong>Sections recherchées</strong><div class="filter-row">${[['recipes','Recettes'],['ingredients','Ingrédients'],['techniques','Techniques'],['equipment','Matériel'],['library','Bibliothèque']].map(([k,l])=>`<button class="btn" data-search-scope="${k}">${l}</button>`).join('')}</div></div><div id="suggestions" class="muted"></div></div>`}
function syncButtons(){$$('[data-search-mode]').forEach(b=>b.classList.toggle('active',b.dataset.searchMode===state.prefs.searchMode));$$('[data-search-op]').forEach(b=>b.classList.toggle('active',b.dataset.searchOp===state.prefs.searchOperator));$$('[data-search-scope]').forEach(b=>b.classList.toggle('active',state.prefs.searchScopes.includes(b.dataset.searchScope)));$('#tokenRow').classList.toggle('hidden',state.prefs.searchMode!=='tokens')}
function parseTokens(raw){return raw.trim().split(/[\s,;]+/).map(x=>x.trim()).filter(x=>x.length>1)}
function renderTokens(){const row=$('#tokenRow');row.innerHTML=state.tokens.map((t,i)=>`<span class="token">${t}<button data-token-remove="${i}" aria-label="Supprimer ${t}">×</button></span>`).join('');$$('[data-token-remove]',row).forEach(b=>b.onclick=()=>{state.tokens.splice(Number(b.dataset.tokenRemove),1);renderTokens();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))})}
export function terms(){if(state.prefs.searchMode==='tokens')return state.tokens.map(normalize);return parseTokens(state.query).map(normalize)}
export function matchesObject(obj){const ts=terms();if(!ts.length)return true;const h=normalize(JSON.stringify(obj));return state.prefs.searchOperator==='or'?ts.some(t=>h.includes(t)):ts.every(t=>h.includes(t))}
export function filteredObjects(type){let pool=[];if(type){pool=(state.data?.[type]||[]).map(x=>({...x,__type:type}))}else{pool=allObjects().filter(x=>state.prefs.searchScopes.includes(x.__type))}pool=pool.filter(matchesObject);if(state.statusFilter&&type==='recipes')pool=pool.filter(x=>x.status===state.statusFilter);return pool}
function updateSuggestions(){const box=$('#suggestions');if(state.prefs.searchMode!=='suggest'||state.query.trim().length<1){box.innerHTML='';return}const q=normalize(state.query.split(/\s+/).at(-1));const values=new Set();allObjects().forEach(o=>{[text(o.title),text(o.name),...(o.tags||[])].filter(Boolean).forEach(v=>{if(normalize(v).includes(q))values.add(v)})});box.innerHTML=[...values].slice(0,8).map(v=>`<button class="chip-btn" data-suggestion="${String(v).replace(/"/g,'&quot;')}">${v}</button>`).join(' ');$$('[data-suggestion]',box).forEach(b=>b.onclick=()=>{const parts=state.query.trim().split(/\s+/);parts[parts.length-1]=b.dataset.suggestion;state.query=parts.join(' ');$('#globalSearch').value=state.query;updateSuggestions();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))})}
export function resetSearch(){state.query='';state.tokens=[];state.statusFilter=null;state.page=1;$('#globalSearch').value='';renderTokens();updateSuggestions();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))}
export function initSearch(){syncButtons();const input=$('#globalSearch');input.addEventListener('input',()=>{state.query=input.value;if(state.prefs.searchMode!=='tokens'){state.page=1;updateSuggestions();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))}});input.addEventListener('keydown',e=>{if(state.prefs.searchMode==='tokens'&&(e.key==='Enter'||e.key===',')){e.preventDefault();const add=parseTokens(input.value);for(const t of add)if(!state.tokens.includes(t))state.tokens.push(t);input.value='';state.query='';renderTokens();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))}});$('#searchConfigBtn').onclick=()=>$('#searchConfigPanel').classList.toggle('hidden');$('#searchResetBtn').onclick=resetSearch;
$$('[data-search-mode]').forEach(b=>b.onclick=()=>{state.prefs.searchMode=b.dataset.searchMode;savePrefs();syncButtons();updateSuggestions();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))});$$('[data-search-op]').forEach(b=>b.onclick=()=>{state.prefs.searchOperator=b.dataset.searchOp;savePrefs();syncButtons();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))});$$('[data-search-scope]').forEach(b=>b.onclick=()=>{const k=b.dataset.searchScope;const a=state.prefs.searchScopes;state.prefs.searchScopes=a.includes(k)?a.filter(x=>x!==k):[...a,k];if(!state.prefs.searchScopes.length){state.prefs.searchScopes=[k];toast('Au moins une section doit rester active')}savePrefs();syncButtons();document.dispatchEvent(new CustomEvent('cuisinex:search-change'))});}
