import {$,$$,state,DEFAULT_PREFS,savePrefs,downloadJSON,readJSONFile,toast,icon} from './core.js';
export function applyTheme(){
  const p=state.prefs,r=document.documentElement.style,b=document.body,h=$('#siteHeader');
  r.setProperty('--primary',p.primary);r.setProperty('--secondary',p.secondary);r.setProperty('--bg1',p.bg1);r.setProperty('--bg2',p.bg2);
  b.classList.toggle('dark',p.theme==='dark'||(p.theme==='system'&&matchMedia('(prefers-color-scheme:dark)').matches));
  h?.classList.toggle('sticky',!!p.headerSticky);h?.classList.toggle('shadow',!!p.headerShadow);
  $('#quickTools')?.classList.toggle('hidden',!p.toolbar);
  $$('.lang-btn').forEach(btn=>btn.classList.toggle('hidden',p.languages?.[btn.dataset.lang]===false));
  renderFooter();
}
export function renderFooter(){
  const f=$('#siteFooter');if(!f)return;f.className=`footer ${state.prefs.footerMode==='classic'?'classic':state.prefs.footerMode==='hidden'?'hidden-footer':'minimal'}`;
  f.innerHTML=state.prefs.footerMode==='classic'?`<div class="wrap footer-inner"><div><strong>🍽️ CuisineX</strong><p>Laboratoire personnel de cuisine technique · P019</p></div><div class="footer-links"><a href="#">Concept</a><a href="#">Sources</a><a href="#">Mentions</a></div></div>`:`<div class="wrap footer-inner"><span>CuisineX · MVP-003</span><span class="footer-links"><a href="#">Concept</a><a href="#">Mentions</a></span></div>`;
}
function syncForm(){const p=state.prefs;['theme','primary','secondary','bg1','bg2','footerMode'].forEach(k=>{const e=$(`#set-${k}`);if(e)e.value=p[k]});['headerSticky','headerShadow','toolbar'].forEach(k=>{const e=$(`#set-${k}`);if(e)e.checked=!!p[k]});$$('[data-lang-visible]').forEach(e=>e.checked=p.languages?.[e.dataset.langVisible]!==false);const d=$('#set-defaultLanguage');if(d)d.value=p.defaultLanguage||'fr';}
function readForm(){const p=state.prefs;p.theme=$('#set-theme').value;p.primary=$('#set-primary').value;p.secondary=$('#set-secondary').value;p.bg1=$('#set-bg1').value;p.bg2=$('#set-bg2').value;p.headerSticky=$('#set-headerSticky').checked;p.headerShadow=$('#set-headerShadow').checked;p.toolbar=$('#set-toolbar').checked;p.footerMode=$('#set-footerMode').value;p.defaultLanguage=$('#set-defaultLanguage').value;p.languages={};$$('[data-lang-visible]').forEach(e=>p.languages[e.dataset.langVisible]=e.checked);applyTheme();}
export function settingsMarkup(){return `<aside id="settingsPanel" class="floating-panel" aria-hidden="true"><div id="settingsHandle" class="floating-head"><strong>⚙ Paramètres CuisineX</strong><button class="mini-btn" id="pinSettings" title="Ancrer">${icon('pin')}</button><button class="mini-btn" id="closeSettings" title="Fermer">${icon('close')}</button></div><div class="floating-body"><div class="field"><label>Mode</label><select id="set-theme"><option value="light">Clair</option><option value="dark">Sombre</option><option value="system">Système</option></select></div><div class="two-col"><label class="field">Primaire<input id="set-primary" type="color"></label><label class="field">Secondaire<input id="set-secondary" type="color"></label><label class="field">Fond A<input id="set-bg1" type="color"></label><label class="field">Fond B<input id="set-bg2" type="color"></label></div><hr><div class="check-grid"><label><input id="set-headerSticky" type="checkbox"> Header sticky</label><label><input id="set-headerShadow" type="checkbox"> Ombre header</label><label><input id="set-toolbar" type="checkbox"> Barre d’outils basse</label></div><div class="field"><label>Footer</label><select id="set-footerMode"><option value="minimal">Discret</option><option value="classic">Classique marqué</option><option value="hidden">Masqué</option></select></div><hr><strong>Langues visibles</strong><div class="check-grid"><label><input type="checkbox" data-lang-visible="fr"> 🇫🇷 Français</label><label><input type="checkbox" data-lang-visible="en"> 🇬🇧 English</label></div><div class="field"><label>Langue par défaut</label><select id="set-defaultLanguage"><option value="fr">🇫🇷 Français</option><option value="en">🇬🇧 English</option></select></div><hr><div class="settings-actions"><button class="btn" id="saveCloseTheme">${icon('save')} Enregistrer & fermer</button><button class="btn" id="exportTheme">${icon('download')} Exporter thème</button><button class="btn" id="importTheme">${icon('upload')} Charger thème</button><button class="btn" id="resetTheme">${icon('reset')} Réinitialiser</button><input id="themeFile" type="file" accept="application/json,.json" hidden></div></div></aside>`}
function makeDraggable(panel,handle){let drag=null;handle.addEventListener('pointerdown',e=>{if(panel.classList.contains('pinned')||e.target.closest('button'))return;const r=panel.getBoundingClientRect();drag={dx:e.clientX-r.left,dy:e.clientY-r.top};handle.setPointerCapture(e.pointerId)});handle.addEventListener('pointermove',e=>{if(!drag)return;panel.style.left=Math.max(4,Math.min(innerWidth-panel.offsetWidth-4,e.clientX-drag.dx))+'px';panel.style.top=Math.max(4,Math.min(innerHeight-panel.offsetHeight-4,e.clientY-drag.dy))+'px';panel.style.right='auto'});handle.addEventListener('pointerup',()=>{drag=null;state.prefs.settingsPosition={left:panel.style.left,top:panel.style.top};savePrefs()})}
export function initThemeUI(){const panel=$('#settingsPanel');syncForm();applyTheme();makeDraggable(panel,$('#settingsHandle'));if(state.prefs.settingsPinned)panel.classList.add('pinned');if(state.prefs.settingsPosition&&!state.prefs.settingsPinned){panel.style.left=state.prefs.settingsPosition.left;panel.style.top=state.prefs.settingsPosition.top;panel.style.right='auto'}
  $('#openSettings').onclick=()=>{panel.classList.add('open');panel.setAttribute('aria-hidden','false');syncForm()};$('#closeSettings').onclick=()=>{panel.classList.remove('open');panel.setAttribute('aria-hidden','true')};$('#pinSettings').onclick=()=>{panel.classList.toggle('pinned');state.prefs.settingsPinned=panel.classList.contains('pinned');if(state.prefs.settingsPinned){panel.style.left='';panel.style.top='';panel.style.right=''}savePrefs()};
  panel.addEventListener('input',()=>{readForm();savePrefs()});panel.addEventListener('change',()=>{readForm();savePrefs()});
  $('#saveCloseTheme').onclick=()=>{readForm();savePrefs();panel.classList.remove('open');toast('Thème enregistré localement')};
  $('#exportTheme').onclick=()=>downloadJSON(`cuisinex-theme-${Date.now()}.json`,{schema:'cuisinex-theme@1',prefs:state.prefs});
  $('#importTheme').onclick=()=>$('#themeFile').click();$('#themeFile').onchange=async e=>{try{const json=await readJSONFile(e.target.files[0]);state.prefs={...DEFAULT_PREFS,...(json.prefs||json)};savePrefs();syncForm();applyTheme();toast('Thème chargé')}catch(err){toast('JSON de thème invalide')}};
  $('#resetTheme').onclick=()=>{state.prefs={...DEFAULT_PREFS,languages:{...DEFAULT_PREFS.languages}};savePrefs();syncForm();applyTheme();toast('Thème réinitialisé')};
}
