const state={lang:'fr',tab:'home',data:null,query:'',detail:null,view:'gallery',tokens:[],searchScope:'all',searchMode:'free',configMode:false,selectedTarget:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const icon=n=>({gear:'<svg class="icon" viewBox="0 0 24 24"><path d="M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21h-4v-.1a1.7 1.7 0 0 0-1.1-1.55 1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3v-4h.1A1.7 1.7 0 0 0 4.65 8.5a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.1A1.7 1.7 0 0 0 15.5 4.65a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.12.37.34.7.6 1 .3.3.68.42 1.1.4h.1v4h-.1A1.7 1.7 0 0 0 19.4 15Z"/></svg>',help:'<svg class="icon" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M9.7 9a2.5 2.5 0 1 1 4.6 1.4c-.8 1-2.3 1.4-2.3 3.1"/><path d="M12 17h.01"/></svg>',sliders:'<svg class="icon" viewBox="0 0 24 24"><path d="M4 6h10M18 6h2M4 12h3M11 12h9M4 18h7M15 18h5"/><circle cx="16" cy="6" r="2"/><circle cx="9" cy="12" r="2"/><circle cx="13" cy="18" r="2"/></svg>',edit:'<svg class="icon" viewBox="0 0 24 24"><path d="m4 20 4.5-1 10-10-3.5-3.5-10 10L4 20Z"/><path d="m13.5 7 3.5 3.5"/></svg>',chev:'<svg class="icon" viewBox="0 0 24 24"><path d="m7 10 5 5 5-5"/></svg>',up:'<svg class="icon" viewBox="0 0 24 24"><path d="m6 14 6-6 6 6"/></svg>',pin:'<svg class="icon" viewBox="0 0 24 24"><path d="m14 4 6 6-3 1-4 4-1 5-3-3-5-5 5-1 4-4 1-3Z"/></svg>',x:'<svg class="icon" viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>'}[n]||'');
const defaults={theme:'light',primary:'#2563eb',secondary:'#0ea5e9',bg:'#eef5ff',bg2:'#dcecff',panel:'#ffffff',text:'#142033',gradientAngle:135,panelAlpha:1,headerSticky:true,headerShadow:true,footerMode:'minimal',toolbar:true,imageSize:220,elementStyles:{},classStyles:{}};
let prefs={...defaults,...JSON.parse(localStorage.getItem('cuisinex-prefs')||'{}')};
function savePrefs(){localStorage.setItem('cuisinex-prefs',JSON.stringify(prefs));}
function applyPrefs(){const r=document.documentElement.style,b=document.body;r.setProperty('--primary',prefs.primary);r.setProperty('--secondary',prefs.secondary);r.setProperty('--bg',prefs.bg);r.setProperty('--bg2',prefs.bg2);r.setProperty('--panel',prefs.panel);r.setProperty('--text',prefs.text);r.setProperty('--gradient-angle',prefs.gradientAngle+'deg');r.setProperty('--panel-alpha',prefs.panelAlpha);r.setProperty('--thumb-size',prefs.imageSize+'px');b.dataset.theme=prefs.theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):prefs.theme;$('#siteHeader')?.classList.toggle('sticky',prefs.headerSticky);$('#siteHeader')?.classList.toggle('shadow',prefs.headerShadow);$('#quickTools')?.classList.toggle('hidden',!prefs.toolbar);renderFooter();}
async function load(lang){state.lang=lang;state.data=await fetch(`runtime/${lang}.json`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});state.detail=null;render();}
function label(key,fr,en){return state.lang==='fr'?fr:en}
function normalized(s){return String(s??'').normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase()}
function allObjects(){if(!state.data)return[];const out=[];['recipes','ingredients','techniques','equipment'].forEach(type=>(state.data[type]||[]).forEach(x=>out.push({...x,__type:type})));return out}
function tabObjects(){return state.tab==='library'?libraryItems():state.tab==='about'?[]:(state.data?.[state.tab]||[]).map(x=>({...x,__type:state.tab}))}
function activeTerms(){const free=state.query.trim()?state.query.trim().split(/\s+/):[];return (state.searchMode==='tokens'?state.tokens:free).map(normalized).filter(Boolean)}
function filteredObjects(){const pool=state.searchScope==='all'&&activeTerms().length?allObjects():tabObjects();const terms=activeTerms();if(!terms.length)return pool;return pool.filter(x=>{const h=normalized(JSON.stringify(x));return terms.every(t=>h.includes(t))})}
function libraryItems(){return [
{id:'RES-CIQUAL',title:'Anses — Ciqual',summary:label('',"Base française de composition nutritionnelle des aliments.","French food composition reference database."),url:'https://ciqual.anses.fr/',tags:['nutrition','institutionnel','ciqual'],__type:'library'},
{id:'RES-TECH-CHOC',title:'Chocolate Tempering: A Perspective',summary:label('',"Publication scientifique utilisée pour la fiche cristallisation/tempérage.","Scientific publication used for the crystallization/tempering technical sheet."),url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC12063059/',tags:['chocolat','science','cristallisation'],__type:'library'},
{id:'RES-VALRHONA',title:'Valrhona — Tempering chocolate',summary:label('',"Repères opératoires fabricant pour les courbes de tempérage.","Manufacturer operating reference for tempering curves."),url:'https://www.valrhona.com/en/l-ecole-valrhona/discover-l-ecole-valrhona/chocolate-terminology/tempering-chocolate',tags:['chocolat','tempérage','fabricant'],__type:'library'}]}
function themeAttrs(id,cls){return `data-theme-id="${esc(id)}" data-theme-class="${esc(cls)}"`}
function localStyle(id,cls){const e=prefs.elementStyles[id],c=prefs.classStyles[cls],x=e||c;if(!x)return'';const s=[];if(x.bg)s.push(`--local-bg:${x.bg}`);if(x.border)s.push(`--local-border:${x.border}`);if(x.opacity!=null)s.push(`--local-opacity:${x.opacity}`);return `style="${s.join(';')}"`}
function editBtn(id,cls){return `<button class="mini-btn theme-edit" title="${label('', 'Modifier ce bloc','Edit this block')}" data-theme-target="${esc(id)}" data-theme-class-target="${esc(cls)}">${icon('edit')}</button>`}
function sectionShell(id,title,body,cls='section',open=true){return `<section id="${esc(id)}" class="mod-section themeable ${open?'':'collapsed'}" ${themeAttrs(id,cls)} ${localStyle(id,cls)}><div class="section-head"><a class="anchor-link" href="#${esc(id)}">#</a><div class="section-title">${esc(title)}</div><div class="section-actions">${editBtn(id,cls)}<button class="mini-btn section-toggle" title="${label('', 'Replier/déplier','Collapse/expand')}">${icon('chev')}</button></div></div><div class="section-body">${body}</div></section>`}
function statusLabel(s){return s==='canonical'?(state.data?.ui?.canonical||'Validée'):(state.data?.ui?.draft||'Brouillon')}
function card(x){const id=x.id||x.title,cls=`card-${x.__type||state.tab}`;const emoji={recipes:'🍲',ingredients:'🥕',techniques:'🧪',equipment:'🔧',library:'📚'}[x.__type]||'•';return `<article class="card themeable" ${themeAttrs(id,cls)} ${localStyle(id,cls)} data-card-id="${esc(id)}" data-card-type="${esc(x.__type||state.tab)}"><button class="mini-btn card-edit theme-edit" data-theme-target="${esc(id)}" data-theme-class-target="${esc(cls)}">${icon('edit')}</button><div class="thumb">${emoji}</div><div>${x.status?`<span class="badge ${x.status==='canonical'?'ok':'warn'}">${esc(statusLabel(x.status))}</span>`:''}<span class="badge">${esc(id)}</span></div><h3>${esc(x.title||x.name)}</h3><p class="muted">${esc(x.summary||x.notes||'')}</p>${x.tags?`<div>${x.tags.map(t=>`<span class="badge">#${esc(t)}</span>`).join('')}</div>`:''}${x.url?`<p><a href="${esc(x.url)}" target="_blank" rel="noopener">${label('', 'Ouvrir la ressource','Open resource')} ↗</a></p>`:''}</article>`}
function renderCollection(items){const n=items.length;const vb=`<div class="viewbar no-print"><span class="result-count">${n} ${label('', 'résultat(s)','result(s)')}</span><span class="spacer"></span>${['gallery','list','compact','table','kanban'].map(v=>`<button class="btn view-btn ${state.view===v?'active':''}" data-view="${v}">${({gallery:'▦',list:'☷',compact:'▥',table:'▤',kanban:'▧'})[v]} ${v}</button>`).join('')}<label class="small">${label('', 'Images','Images')} <input id="imageSize" type="range" min="80" max="280" value="${prefs.imageSize}"></label></div>`;
if(state.view==='table'){const rows=items.map(x=>`<tr data-row-id="${esc(x.id)}" data-row-type="${esc(x.__type)}"><td>${esc(x.id)}</td><td>${esc(x.title||x.name)}</td><td>${esc(x.status||x.kind||'')}</td><td>${esc(x.summary||x.notes||'')}</td></tr>`).join('');return vb+`<div class="panel"><table class="table"><thead><tr><th>ID</th><th>${label('', 'Titre','Title')}</th><th>${label('', 'Statut','Status')}</th><th>${label('', 'Résumé','Summary')}</th></tr></thead><tbody>${rows}</tbody></table></div>`}
if(state.view==='kanban'){const groups={canonical:[],draft:[],other:[]};items.forEach(x=>(groups[x.status]||groups.other).push(x));return vb+`<div class="grid kanban">${Object.entries(groups).filter(([,a])=>a.length).map(([k,a])=>`<div class="kanban-col"><h3>${k}</h3>${a.map(card).join('')}</div>`).join('')}</div>`}
return vb+`<div class="grid ${state.view==='list'?'list':state.view==='compact'?'compact':''}">${items.map(card).join('')}</div>`}
function homeView(){const totals={r:state.data.recipes?.length||0,i:state.data.ingredients?.length||0,t:state.data.techniques?.length||0,e:state.data.equipment?.length||0};const hero=`<div class="hero"><div class="panel hero-card themeable" ${themeAttrs('hero','hero')} ${localStyle('hero','hero')}><button class="mini-btn card-edit theme-edit" data-theme-target="hero" data-theme-class-target="hero">${icon('edit')}</button><span class="badge">MVP-002</span><h1>🍽️ CuisineX</h1><p>${label('',"Laboratoire personnel de cuisine technique : recettes reproductibles, ingrédients documentés, sciences culinaires et moteurs de calcul.","Personal technical cooking laboratory: reproducible recipes, documented ingredients, culinary science and calculation engines.")}</p><p class="muted">${label('',"Français = source maître · anglais = traduction dérivée · données runtime en JSON.","French = master source · English = derived translation · JSON runtime data.")}</p></div><div class="panel hero-metric"><div><strong>${totals.r}</strong><br>${label('', 'recettes','recipes')}<br><span class="muted">${totals.i} ${label('', 'ingrédients','ingredients')} · ${totals.t} ${label('', 'techniques','techniques')}</span></div></div></div>`;
const sections=[['recipes','🍲',label('', 'Recettes','Recipes'),label('', 'Protocoles détaillés, variantes, nutrition et relations techniques.','Detailed protocols, variants, nutrition and technical relations.')],['ingredients','🥕',label('', 'Ingrédients','Ingredients'),label('', 'Ciqual et produits personnels documentés par emballage.','Ciqual and personal products documented from packaging.')],['techniques','🧪',label('', 'Techniques & astuces','Techniques & tips'),label('', 'Fusion, cristallisation, œufs, gélifiants, températures critiques.','Melting, crystallization, eggs, gelling agents, critical temperatures.')],['equipment','🔧',label('', 'Matériel','Equipment'),label('', 'Inventaire du matériel réellement disponible.','Inventory of equipment actually available.')],['library','📚',label('', 'Bibliothèque','Library'),label('', 'Sources scientifiques, institutionnelles, sites et ressources.','Scientific, institutional, web and reference resources.')]];
const cards=sections.map(([tab,em,t,d])=>`<article class="card" data-nav-tab="${tab}"><div class="thumb">${em}</div><h3>${t}</h3><p class="muted">${d}</p></article>`).join('');return sectionShell('home-hero',label('', 'Accueil','Home'),hero,'hero-section')+sectionShell('home-sections',label('', 'Explorer CuisineX','Explore CuisineX'),`<div class="grid">${cards}</div>`,'home-sections')+sectionShell('home-search',label('', 'Recherche globale','Global search'),`<p>${label('',"Utilise la barre de recherche du header. Le bouton de réglages à droite de la barre permet de choisir recherche libre, suggestions ou jetons, et de limiter la portée.","Use the header search bar. The settings button lets you choose free text, suggestions or tokens and control the search scope.")}</p>`,'search-help')}
function aboutView(){return sectionShell('about-concept',label('', 'Concept','Concept'),`<h2>nLab CuisineX</h2><p>${label('',"CuisineX sépare le contenu auteur en Markdown, les données structurées, la compilation et le viewer public. Le français est la langue canonique ; les autres langues sont des traductions dérivées.","CuisineX separates Markdown authoring, structured data, compilation and the public viewer. French is canonical; other languages are derived translations.")}</p>`,'editorial')+sectionShell('about-data',label('', 'Modèle de données','Data model'),`<p><strong>Markdown → JSON runtime → viewer générique.</strong></p><p>${label('',"Les recettes, ingrédients, techniques et matériels sont reliés par ID. Les masses en grammes sont canoniques ; les volumes sont convertis avec une densité documentée.","Recipes, ingredients, techniques and equipment are linked by IDs. Gram masses are canonical; volumes are converted using documented density.")}</p>`,'editorial')}
function urlFor(type,id){const u=new URL(location.href);u.search='';u.searchParams.set('lang',state.lang);u.searchParams.set('type',type);u.searchParams.set('id',id);return u.toString()}
function qrFor(type,id){return `https://quickchart.io/qr?size=180&text=${encodeURIComponent(urlFor(type,id))}`}
function resolveIngredient(id){return state.data.ingredients.find(x=>x.id===id)}
function sourcesBlock(src=[]){if(!src.length)return'';return sectionShell('sources',state.data.ui.sources||'Sources',src.map(s=>`<p class="source"><strong>${esc(s.title)}</strong>${s.type?` <span class="badge">${esc(s.type)}</span>`:''}${s.url?`<br><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.url)}</a>`:''}</p>`).join(''),'sources')}
function relationButtons(rel={}){const ids=[];Object.values(rel||{}).flat().forEach(v=>typeof v==='string'&&ids.push(v));return ids.map(id=>{const type=id.startsWith('TECH')||id.startsWith('TIP')?'techniques':id.startsWith('REC')?'recipes':id.startsWith('EQP')?'equipment':'ingredients';return `<button class="btn inline-link" data-open-type="${type}" data-open-id="${esc(id)}">${esc(id)}</button> `}).join('')||'—'}
function recipeDetail(r){const head=`<div class="detail-head"><div><span class="badge ${r.status==='canonical'?'ok':'warn'}">${esc(statusLabel(r.status))}</span><span class="badge">${esc(r.id)}</span><h1>${esc(r.title)}</h1><p>${esc(r.summary||'')}</p>${r.chef?`<p><strong>${esc(r.chef)}</strong></p>`:''}</div><div><img class="qr" src="${qrFor('recipe',r.id)}" alt="QR"><br><button class="btn no-print" onclick="window.print()">${esc(state.data.ui.print)}</button></div></div>`;
const ing=(r.ingredients||[]).map(i=>{const p=resolveIngredient(i.id);return `<li><button class="btn inline-link" data-open-type="ingredients" data-open-id="${esc(i.id)}">${esc(p?.name||i.id)}</button> — <strong>${esc(i.mass_g)} g</strong>${i.breakdown?` <span class="muted">(${esc(i.breakdown)})</span>`:''}</li>`}).join('');
const temps=(r.temperatures||[]).map(t=>`<tr><td>${esc(t.step)}</td><td>${esc(t.target_c)} °C</td><td>${esc(t.range)}</td></tr>`).join('');
return `<button class="btn back no-print">← ${label('', 'Retour','Back')}</button>`+sectionShell(`rec-${r.id}-intro`,r.title,head,'recipe-intro')+sectionShell(`rec-${r.id}-ingredients`,state.data.ui.ingredients||'Ingrédients',`<ul>${ing||'<li>—</li>'}</ul>${r.formula?`<p><strong>${label('', 'Formulation','Formula')} :</strong> ${label('', 'chocolat','chocolate')} ${r.formula.chocolate_pct}% · ${label('', 'crème','cream')} ${r.formula.cream_pct}% · ${label('', 'sucre ajouté','added sugar')} ${r.formula.added_sugar_g} g</p>`:''}`,'recipe-section')+sectionShell(`rec-${r.id}-method`,label('', 'Procédé','Method'),`<ol>${(r.steps||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ol>`,'recipe-section')+sectionShell(`rec-${r.id}-technical`,state.data.ui.technical||'Données techniques',temps?`<table class="table"><thead><tr><th>${label('', 'Étape','Step')}</th><th>${label('', 'Cible','Target')}</th><th>${label('', 'Plage','Range')}</th></tr></thead><tbody>${temps}</tbody></table>`:'—','technical')+sectionShell(`rec-${r.id}-links`,label('', 'Relations','Relations'),relationButtons(r.relations),'relations')}
function ingredientDetail(x){const n=x.nutrition_per_100g||x.nutrition_per_100ml||{};const head=`<div class="detail-head"><div><span class="badge">${esc(x.id)}</span><h1>${esc(x.name)}</h1><p>${esc(x.brand||'')}</p></div><img class="qr" src="${qrFor('ingredient',x.id)}" alt="QR"></div>`;return `<button class="btn back no-print">← ${label('', 'Retour','Back')}</button>`+sectionShell(`ing-${x.id}-intro`,x.name,head,'ingredient-intro')+sectionShell(`ing-${x.id}-identity`,label('', 'Identité','Identity'),`<p>${x.ean?`EAN: <strong>${esc(x.ean)}</strong><br>`:''}${x.ingredients_text?`${label('', 'Ingrédients','Ingredients')}: ${esc(x.ingredients_text)}<br>`:''}${label('', 'Source','Source')}: ${esc(x.source||x.source_url||'—')}</p><p>${esc(x.notes||'')}</p>`,'ingredient-section')+sectionShell(`ing-${x.id}-nutrition`,label('', 'Nutrition','Nutrition'),`<table class="table">${Object.entries(n).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${v==null?'—':esc(v)}</td></tr>`).join('')}</table>`,'nutrition')}
function techniqueDetail(x){const poly=x.polymorphs?`<table class="table"><thead><tr><th>${label('', 'Forme','Form')}</th><th>${label('', 'Fusion','Melting')}</th></tr></thead><tbody>${x.polymorphs.map(p=>`<tr><td>${esc(p.form)}</td><td>${esc(p.melting_c)} °C</td></tr>`).join('')}</tbody></table>`:'';const temp=x.tempering?`<table class="table"><thead><tr><th>Type</th><th>${label('', 'Fonte','Melt')}</th><th>${label('', 'Cristallisation','Crystallization')}</th><th>${label('', 'Travail','Work')}</th></tr></thead><tbody>${x.tempering.map(p=>`<tr><td>${esc(p.type)}</td><td>${esc(p.melt)}</td><td>${esc(p.crystallize)}</td><td>${esc(p.work)}</td></tr>`).join('')}</tbody></table>`:'';return `<button class="btn back no-print">← ${label('', 'Retour','Back')}</button>`+sectionShell(`tech-${x.id}-intro`,x.title,`<div class="detail-head"><div><span class="badge">${esc(x.id)}</span><h1>${esc(x.title)}</h1><p>${esc(x.summary)}</p></div><img class="qr" src="${qrFor('technique',x.id)}" alt="QR"></div>`,'technique-intro')+(poly?sectionShell(`tech-${x.id}-poly`,label('', 'Polymorphes du beurre de cacao','Cocoa butter polymorphs'),poly,'technical'):'')+(temp?sectionShell(`tech-${x.id}-temper`,label('', 'Courbes de tempérage','Tempering curves'),temp+(x.warning?`<p><strong>⚠ ${esc(x.warning)}</strong></p>`:''),'technical'):'')+sourcesBlock(x.sources)}
function genericDetail(x,type){return `<button class="btn back no-print">← ${label('', 'Retour','Back')}</button>`+sectionShell(`${type}-${x.id}`,x.title||x.name,`<div class="detail-head"><div><span class="badge">${esc(x.id)}</span><h1>${esc(x.title||x.name)}</h1><p>${esc(x.notes||x.summary||'')}</p></div><img class="qr" src="${qrFor(type,x.id)}" alt="QR"></div>`,'generic')}
function detailView(){const {type,id}=state.detail;const arr=type==='library'?libraryItems():(state.data[type]||[]);const x=arr.find(i=>i.id===id);if(!x)return '<p>Not found</p>';if(type==='recipes')return recipeDetail(x);if(type==='ingredients')return ingredientDetail(x);if(type==='techniques')return techniqueDetail(x);return genericDetail(x,type)}
function searchResultsView(){const items=filteredObjects();return sectionShell('search-results',label('', 'Résultats de recherche','Search results'),renderCollection(items),'search-results')}
function listView(){if(state.tab==='home')return homeView();if(state.tab==='about')return aboutView();const items=filteredObjects();const title={recipes:state.data.ui.recipes,ingredients:state.data.ui.ingredients,techniques:state.data.ui.techniques,equipment:state.data.ui.equipment,library:label('', 'Bibliothèque','Library')}[state.tab]||state.tab;return sectionShell(`list-${state.tab}`,title,renderCollection(items),`list-${state.tab}`)}
function render(){if(!state.data)return;document.documentElement.lang=state.lang;$('#lang').value=state.lang;$('#search').placeholder=state.data.ui.search;$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));$('#app').innerHTML=state.detail?detailView():(state.searchScope==='all'&&activeTerms().length?searchResultsView():listView());document.body.classList.toggle('config-mode',state.configMode);applyPrefs();bindDynamic();renderTokens();updateHelp()}
function open(type,id){state.tab=type;state.detail={type,id};history.replaceState(null,'',`?lang=${state.lang}&type=${encodeURIComponent(type)}&id=${encodeURIComponent(id)}`);render()}
function bindDynamic(){ $$('.card[data-card-id]').forEach(c=>c.onclick=e=>{if(e.target.closest('.theme-edit')||e.target.closest('a'))return;open(c.dataset.cardType,c.dataset.cardId)});$$('[data-nav-tab]').forEach(c=>c.onclick=()=>{state.tab=c.dataset.navTab;state.detail=null;state.query='';render()});$$('[data-open-id]').forEach(b=>b.onclick=e=>{e.stopPropagation();open(b.dataset.openType,b.dataset.openId)});$$('.back').forEach(b=>b.onclick=()=>{state.detail=null;history.replaceState(null,'',`?lang=${state.lang}`);render()});$$('.section-toggle').forEach(b=>b.onclick=()=>b.closest('.mod-section').classList.toggle('collapsed'));$$('.theme-edit').forEach(b=>b.onclick=e=>{e.stopPropagation();selectThemeTarget(b.dataset.themeTarget,b.dataset.themeClassTarget)});$$('.view-btn').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});$('#imageSize')?.addEventListener('input',e=>{prefs.imageSize=+e.target.value;savePrefs();applyPrefs()});$$('tbody tr[data-row-id]').forEach(r=>r.onclick=()=>open(r.dataset.rowType,r.dataset.rowId)) }
function openPanel(id){$('#'+id).classList.remove('hidden')}
function closePanel(id){$('#'+id).classList.add('hidden')}
function togglePanel(id){$('#'+id).classList.toggle('hidden')}
function makeDraggable(panel){const head=panel.querySelector('.floating-head');let drag=false,ox=0,oy=0;head.addEventListener('pointerdown',e=>{if(panel.classList.contains('docked')||e.target.closest('button'))return;drag=true;const r=panel.getBoundingClientRect();ox=e.clientX-r.left;oy=e.clientY-r.top;head.setPointerCapture(e.pointerId)});head.addEventListener('pointermove',e=>{if(!drag)return;panel.style.left=Math.max(0,e.clientX-ox)+'px';panel.style.top=Math.max(0,e.clientY-oy)+'px';panel.style.right='auto'});head.addEventListener('pointerup',()=>drag=false)}
function selectThemeTarget(id,cls){state.selectedTarget={id,cls};$$('.theme-target').forEach(x=>x.classList.remove('theme-target'));document.querySelector(`[data-theme-id="${CSS.escape(id)}"]`)?.classList.add('theme-target');$('#targetName').textContent=`${id} · ${cls}`;openPanel('settingsPanel')}
function applyScopedStyle(){const scope=document.querySelector('input[name="scope"]:checked')?.value||'element',bg=$('#localBg').value,border=$('#localBorder').value,opacity=+$('#localOpacity').value;if(scope==='global'){prefs.panel=bg;prefs.panelAlpha=opacity;document.documentElement.style.setProperty('--line',border)}else if(state.selectedTarget){const target=scope==='class'?prefs.classStyles:prefs.elementStyles;const key=scope==='class'?state.selectedTarget.cls:state.selectedTarget.id;target[key]={bg,border,opacity}}savePrefs();render()}
function renderTokens(){const box=$('#tokens');if(!box)return;box.innerHTML=state.tokens.map((t,i)=>`<span class="token">${esc(t)}<button data-token-index="${i}">×</button></span>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.tokens.splice(+b.dataset.tokenIndex,1);render()})}
function syncSettingsUI(){if(!$('#themeMode'))return;$('#themeMode').value=prefs.theme;$('#primaryColor').value=prefs.primary;$('#secondaryColor').value=prefs.secondary;$('#bgColor').value=prefs.bg;$('#bg2Color').value=prefs.bg2;$('#panelColor').value=prefs.panel;$('#textColor').value=prefs.text;$('#gradientAngle').value=prefs.gradientAngle;$('#panelAlpha').value=prefs.panelAlpha;$('#headerSticky').checked=prefs.headerSticky;$('#headerShadow').checked=prefs.headerShadow;$('#footerMode').value=prefs.footerMode;$('#configMode').checked=state.configMode;$('#toolbarVisible').checked=prefs.toolbar;$('#searchMode').value=state.searchMode;$('#searchScope').value=state.searchScope}
function updateHelp(){const h=$('#helpContent');if(!h)return;const map={home:["Accueil","Le héros et toutes les sections sont repliables. Active le mode configuration pour modifier un élément, une classe ou le thème global."],recipes:["Recettes","Clique une carte pour ouvrir la fiche. Chaque sous-section est repliable et possède une ancre."],ingredients:["Ingrédients","Les fiches produits et Ciqual sont reliées par ID aux recettes."],techniques:["Techniques","Les sources sont affichées dans chaque fiche technique."],equipment:["Matériel","Inventaire progressif du matériel réellement disponible."],library:["Bibliothèque","Ressources classées par tags ; la recherche globale les indexera dans une prochaine itération."],about:["Concept","Architecture Markdown auteur → JSON runtime → viewer générique."]};const [t,d]=map[state.tab]||map.home;h.innerHTML=`<h3>${t}</h3><p>${d}</p>`}
function renderFooter(){const f=$('#siteFooter');if(!f)return;f.className=prefs.footerMode==='classic'?'footer-classic':prefs.footerMode==='minimal'?'footer-minimal':'hidden';f.innerHTML=`<div class="wrap footer-row"><span>🍽️ nLab CuisineX · ${state.data?.meta?.build||'MVP'}</span><span>${label('', 'Projet personnel technique','Personal technical project')}</span></div>`}
function setThemeControls(){['themeMode','primaryColor','secondaryColor','bgColor','bg2Color','panelColor','textColor','gradientAngle','panelAlpha','headerSticky','headerShadow','footerMode','toolbarVisible'].forEach(id=>$('#'+id)?.addEventListener('input',()=>{prefs.theme=$('#themeMode').value;prefs.primary=$('#primaryColor').value;prefs.secondary=$('#secondaryColor').value;prefs.bg=$('#bgColor').value;prefs.bg2=$('#bg2Color').value;prefs.panel=$('#panelColor').value;prefs.text=$('#textColor').value;prefs.gradientAngle=+$('#gradientAngle').value;prefs.panelAlpha=+$('#panelAlpha').value;prefs.headerSticky=$('#headerSticky').checked;prefs.headerShadow=$('#headerShadow').checked;prefs.footerMode=$('#footerMode').value;prefs.toolbar=$('#toolbarVisible').checked;savePrefs();applyPrefs()}));$('#configMode')?.addEventListener('change',e=>{state.configMode=e.target.checked;render()});$('#applyLocalStyle')?.addEventListener('click',applyScopedStyle);$('#resetTheme')?.addEventListener('click',()=>{prefs={...defaults,elementStyles:{},classStyles:{}};savePrefs();render();syncSettingsUI()})}
$('#search').addEventListener('keydown',e=>{if(state.searchMode==='tokens'&&e.key==='Enter'){e.preventDefault();const v=e.target.value.trim();if(v){state.tokens.push(v);e.target.value='';state.query='';render()}}});$('#search').addEventListener('input',e=>{state.query=e.target.value;state.detail=null;render()});$('#lang').addEventListener('change',e=>load(e.target.value));$$('.nav button').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.detail=null;state.query='';state.tokens=[];render()});$('#settingsBtn').onclick=()=>{togglePanel('settingsPanel');syncSettingsUI()};$('#helpBtn').onclick=()=>togglePanel('helpPanel');$('#searchSettingsBtn').onclick=()=>togglePanel('searchPanel');$$('[data-close-panel]').forEach(b=>b.onclick=()=>closePanel(b.dataset.closePanel));$$('[data-dock-panel]').forEach(b=>b.onclick=()=>$('#'+b.dataset.dockPanel).classList.toggle('docked'));$('#collapseAll').onclick=()=>$$('.mod-section').forEach(x=>x.classList.add('collapsed'));$('#expandAll').onclick=()=>$$('.mod-section').forEach(x=>x.classList.remove('collapsed'));$('#toTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});$('#hideToolbar').onclick=()=>{prefs.toolbar=false;savePrefs();applyPrefs()};$('#searchMode').onchange=e=>{state.searchMode=e.target.value;renderTokens()};$('#searchScope').onchange=e=>{state.searchScope=e.target.value;render()};setThemeControls();['settingsPanel','helpPanel'].forEach(id=>makeDraggable($('#'+id)));
const p=new URLSearchParams(location.search);const initialLang=p.get('lang')||'fr';load(initialLang).then(()=>{syncSettingsUI();const t=p.get('type'),id=p.get('id');if(t&&id)open(t==='recipe'?'recipes':t==='ingredient'?'ingredients':t==='technique'?'techniques':t,id)}).catch(e=>{$('#app').innerHTML=`<div class="panel"><h1>Erreur de chargement</h1><p>${esc(e.message)}</p></div>`});
