const state={lang:'fr',tab:'recipes',data:null,query:'',detail:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function load(lang){state.lang=lang;state.data=await fetch(`runtime/${lang}.json`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()});state.detail=null;render();}
function urlFor(type,id){const u=new URL(location.href);u.search='';u.searchParams.set('lang',state.lang);u.searchParams.set('type',type);u.searchParams.set('id',id);return u.toString();}
function qrFor(type,id){return `https://quickchart.io/qr?size=180&text=${encodeURIComponent(urlFor(type,id))}`;}
function allForTab(){if(!state.data)return[];return state.data[state.tab]||[];}
function searchable(x){return JSON.stringify(x).normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase();}
function filtered(){const q=state.query.trim().normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase();return q?allForTab().filter(x=>searchable(x).includes(q)):allForTab();}
function labelStatus(s){return s==='canonical'?state.data.ui.canonical:state.data.ui.draft;}
function card(x){return `<article class="card" data-id="${esc(x.id)}"><div><span class="badge ${x.status==='canonical'?'ok':'warn'}">${esc(labelStatus(x.status))}</span><span class="badge">${esc(x.id)}</span></div><h3>${esc(x.title||x.name)}</h3><p class="muted">${esc(x.summary||x.notes||'')}</p></article>`;}
function home(){const u=state.data.ui;return `<section class="hero"><div class="panel"><h1>🍽️ nLab CuisineX</h1><p>${state.lang==='fr'?'MVP technique piloté par données JSON : recettes, ingrédients, techniques et matériel liés par ID.':'Technical JSON-driven MVP: recipes, ingredients, techniques and equipment linked by IDs.'}</p><p class="muted">${state.lang==='fr'?'Français = source maître · anglais = traduction dérivée.':'French = master source · English = derived translation.'}</p></div><div class="panel"><strong>${esc(state.data.meta.build)}</strong><p class="muted">${esc(state.data.meta.status)}</p></div></section><section class="grid">${filtered().map(card).join('')}</section>`;}
function resolveIngredient(id){return state.data.ingredients.find(x=>x.id===id);}
function sourcesBlock(src=[]){if(!src.length)return'';return `<section><h2>${esc(state.data.ui.sources)}</h2>${src.map(s=>`<p class="source"><strong>${esc(s.title)}</strong>${s.type?` <span class="badge">${esc(s.type)}</span>`:''}${s.url?`<br><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.url)}</a>`:''}</p>`).join('')}</section>`;}
function recipeDetail(r){const ing=(r.ingredients||[]).map(i=>{const p=resolveIngredient(i.id);return `<li><button class="btn inline-link" data-open-type="ingredients" data-open-id="${esc(i.id)}">${esc(p?.name||i.id)}</button> — <strong>${esc(i.mass_g)} g</strong>${i.breakdown?` <span class="muted">(${esc(i.breakdown)})</span>`:''}</li>`}).join('');const temps=(r.temperatures||[]).map(t=>`<tr><td>${esc(t.step)}</td><td>${esc(t.target_c)} °C</td><td>${esc(t.range)}</td></tr>`).join('');return `<button class="back no-print">← ${state.lang==='fr'?'Retour':'Back'}</button><article class="panel"><div class="detail-head"><div><span class="badge ${r.status==='canonical'?'ok':'warn'}">${esc(labelStatus(r.status))}</span><span class="badge">${esc(r.id)}</span><h1>${esc(r.title)}</h1><p>${esc(r.summary||'')}</p>${r.chef?`<p><strong>${esc(r.chef)}</strong></p>`:''}</div><div><img class="qr" src="${qrFor('recipe',r.id)}" alt="QR"><br><button class="btn no-print" onclick="window.print()">${esc(state.data.ui.print)}</button></div></div><div class="detail-grid"><div><h2>${esc(state.data.ui.ingredients)}</h2><ul class="list">${ing||'<li>—</li>'}</ul>${r.formula?`<h2>${state.lang==='fr'?'Formulation':'Formula'}</h2><p>${state.lang==='fr'?'Chocolat':'Chocolate'}: <strong>${esc(r.formula.chocolate_pct)} %</strong> · ${state.lang==='fr'?'Crème':'Cream'}: <strong>${esc(r.formula.cream_pct)} %</strong> · ${state.lang==='fr'?'Sucre ajouté':'Added sugar'}: <strong>${esc(r.formula.added_sugar_g)} g</strong></p>`:''}<h2>${state.lang==='fr'?'Procédé':'Method'}</h2><ol class="list">${(r.steps||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div><aside><h2>${esc(state.data.ui.technical)}</h2>${temps?`<table class="table"><thead><tr><th>${state.lang==='fr'?'Étape':'Step'}</th><th>${state.lang==='fr'?'Cible':'Target'}</th><th>${state.lang==='fr'?'Plage':'Range'}</th></tr></thead><tbody>${temps}</tbody></table>`:'<p>—</p>'}<h3>${state.lang==='fr'?'Liens':'Links'}</h3>${relationButtons(r.relations)}</aside></div></article>`;}
function relationButtons(rel={}){const ids=[];Object.values(rel||{}).flat().forEach(v=>{if(typeof v==='string')ids.push(v)});return ids.map(id=>{let type=id.startsWith('TECH')||id.startsWith('TIP')?'techniques':id.startsWith('REC')?'recipes':id.startsWith('EQP')?'equipment':'ingredients';return `<button class="btn inline-link" data-open-type="${type}" data-open-id="${esc(id)}">${esc(id)}</button> `}).join('')||'—';}
function ingredientDetail(x){const n=x.nutrition_per_100g||x.nutrition_per_100ml||{};return `<button class="back no-print">← ${state.lang==='fr'?'Retour':'Back'}</button><article class="panel"><div class="detail-head"><div><span class="badge">${esc(x.id)}</span><h1>${esc(x.name)}</h1><p>${esc(x.brand||'')}</p></div><img class="qr" src="${qrFor('ingredient',x.id)}" alt="QR"></div><div class="detail-grid"><div><h2>${state.lang==='fr'?'Identité':'Identity'}</h2><p>${x.ean?`EAN: <strong>${esc(x.ean)}</strong><br>`:''}${x.ingredients_text?`${state.lang==='fr'?'Ingrédients':'Ingredients'}: ${esc(x.ingredients_text)}<br>`:''}${state.lang==='fr'?'Source':'Source'}: ${esc(x.source||x.source_url||'—')}</p><p>${esc(x.notes||'')}</p></div><aside><h2>${state.lang==='fr'?'Nutrition étiquette':'Label nutrition'}</h2><table class="table">${Object.entries(n).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${v==null?'—':esc(v)}</td></tr>`).join('')}</table></aside></div></article>`;}
function techniqueDetail(x){const poly=x.polymorphs?`<h2>${state.lang==='fr'?'Polymorphes du beurre de cacao':'Cocoa butter polymorphs'}</h2><table class="table"><thead><tr><th>Forme</th><th>${state.lang==='fr'?'Fusion':'Melting'}</th></tr></thead><tbody>${x.polymorphs.map(p=>`<tr><td>${esc(p.form)}</td><td>${esc(p.melting_c)} °C</td></tr>`).join('')}</tbody></table>`:'';const temp=x.tempering?`<h2>${state.lang==='fr'?'Courbes de tempérage':'Tempering curves'}</h2><table class="table"><thead><tr><th>Type</th><th>${state.lang==='fr'?'Fonte':'Melt'}</th><th>${state.lang==='fr'?'Cristallisation':'Crystallize'}</th><th>${state.lang==='fr'?'Travail':'Work'}</th></tr></thead><tbody>${x.tempering.map(p=>`<tr><td>${esc(p.type)}</td><td>${esc(p.melt)}</td><td>${esc(p.crystallize)}</td><td>${esc(p.work)}</td></tr>`).join('')}</tbody></table>`:'';return `<button class="back no-print">← ${state.lang==='fr'?'Retour':'Back'}</button><article class="panel"><div class="detail-head"><div><span class="badge">${esc(x.id)}</span><h1>${esc(x.title)}</h1><p>${esc(x.summary)}</p></div><img class="qr" src="${qrFor('technique',x.id)}" alt="QR"></div>${poly}${temp}${x.warning?`<p><strong>⚠ ${esc(x.warning)}</strong></p>`:''}${sourcesBlock(x.sources)}</article>`;}
function genericDetail(x,type){return `<button class="back no-print">← ${state.lang==='fr'?'Retour':'Back'}</button><article class="panel"><div class="detail-head"><div><span class="badge">${esc(x.id)}</span><h1>${esc(x.title||x.name)}</h1><p>${esc(x.notes||x.summary||'')}</p></div><img class="qr" src="${qrFor(type,x.id)}" alt="QR"></div></article>`;}
function detail(){const {type,id}=state.detail;const arr=state.data[type]||[];const x=arr.find(i=>i.id===id);if(!x)return `<p>Not found</p>`;if(type==='recipes')return recipeDetail(x);if(type==='ingredients')return ingredientDetail(x);if(type==='techniques')return techniqueDetail(x);return genericDetail(x,type);}
function render(){if(!state.data)return;document.documentElement.lang=state.lang;$('#lang').value=state.lang;$('#search').placeholder=state.data.ui.search;document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));$('#app').innerHTML=state.detail?detail():home();bind();}
function open(type,id){state.tab=type;state.detail={type,id};history.replaceState(null,'',`?lang=${state.lang}&type=${encodeURIComponent(type)}&id=${encodeURIComponent(id)}`);render();}
function bind(){document.querySelectorAll('.card').forEach(c=>c.onclick=()=>open(state.tab,c.dataset.id));document.querySelectorAll('[data-open-id]').forEach(b=>b.onclick=e=>{e.stopPropagation();open(b.dataset.openType,b.dataset.openId)});document.querySelectorAll('.back').forEach(b=>b.onclick=()=>{state.detail=null;history.replaceState(null,'',`?lang=${state.lang}`);render()});}
$('#search').addEventListener('input',e=>{state.query=e.target.value;state.detail=null;render()});$('#lang').addEventListener('change',e=>load(e.target.value));document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.detail=null;render()});
const p=new URLSearchParams(location.search);const initialLang=p.get('lang')||'fr';load(initialLang).then(()=>{const t=p.get('type'),id=p.get('id');if(t&&id)open(t==='recipe'?'recipes':t==='ingredient'?'ingredients':t==='technique'?'techniques':t,id)}).catch(e=>{$('#app').innerHTML=`<div class="panel"><h1>Erreur de chargement</h1><p>${esc(e.message)}</p></div>`});
